"""Adapt MCP image results for native multimodal or text-only model hosts.

Handlers keep returning the repository's raw content dictionaries. At the shared MCP boundary,
``QWEN_MM_NATIVE_MODE=1`` (the default) passes image blocks through unchanged, while mode ``0``
replaces them in place with captions generated by the configured OpenAI-compatible VL endpoint.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from shared.env import get_bool_env

log = logging.getLogger(__name__)

_CAPTION_BATCH_SIZE = 8
_CAPTION_MAX_TOKENS = 32 * 1024
_PERMANENT_ENDPOINT_STATUSES = frozenset({400, 401, 402, 403, 404, 405, 422})
_MISSING_KEY_TEXT = (
    "QWEN_MM_NATIVE_MODE=0 requires a non-empty DASHSCOPE_API_KEY for the configured OpenAI-compatible endpoint."
)
_CAPTION_FAILURE_TEXT = (
    "caption generation failed; check DASHSCOPE_API_KEY, DASHSCOPE_BASE_URL, and QWEN_MM_API_VL_MODEL."
)
_CAPTION_PROMPT = """Describe each input image for a text-only language model.

For every image, preserve the information needed to reason about it: faithfully transcribe visible
text, tables, labels, and values; describe charts, diagrams, UI state, objects, and spatial
relationships; distinguish observed details from uncertainty. Do not invent unseen details.

Return JSON only, exactly in this shape:
{"captions":["caption for image 1","caption for image 2"]}

The captions array must contain exactly one non-empty string per image, in input order.
"""


def native_mode_enabled() -> bool:
    """Return the call-time value of ``QWEN_MM_NATIVE_MODE`` (default: enabled).

    Invalid values fail safe to native mode: they must not silently upload tool-result images to an
    external caption endpoint.
    """
    return get_bool_env("QWEN_MM_NATIVE_MODE", default=True)


def adapt_content_blocks(blocks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return content blocks suitable for the configured model mode.

    Native mode is a zero-work pass-through. In fallback mode, valid image blocks are captioned in
    small batches and replaced at their original positions; all existing text and malformed/unknown
    blocks are preserved for the normal MCP conversion layer.
    """
    if native_mode_enabled():
        return blocks

    positions = [
        i
        for i, block in enumerate(blocks)
        if isinstance(block, dict) and block.get("type") == "image" and isinstance(block.get("data"), str)
    ]
    if not positions:
        return blocks

    images = [blocks[i] for i in positions]
    from shared.api_openai import resolve_openai_endpoint, resolve_vl_model

    base_url, api_key = resolve_openai_endpoint({})
    api_key = api_key.strip()
    if not api_key or api_key == "EMPTY":
        captions: list[str | None] = [None] * len(images)
        failure_text = _MISSING_KEY_TEXT
    else:
        captions = _caption_images(
            images,
            base_url=base_url,
            api_key=api_key,
            model=resolve_vl_model(),
        )
        failure_text = _CAPTION_FAILURE_TEXT

    adapted = list(blocks)
    for position, caption in zip(positions, captions):
        if caption:
            adapted[position] = {
                "type": "text",
                "text": f"[Generated visual caption]\n{caption}",
            }
        else:
            adapted[position] = {
                "type": "text",
                "text": f"[Visual content unavailable: {failure_text}]",
            }
    return adapted


def _caption_images(
    images: list[dict[str, Any]],
    *,
    base_url: str,
    api_key: str,
    model: str,
) -> list[str | None]:
    """Caption images in bounded multi-image requests, preserving input order."""
    captions: list[str | None] = []
    for start in range(0, len(images), _CAPTION_BATCH_SIZE):
        batch = images[start : start + _CAPTION_BATCH_SIZE]
        try:
            captions.extend(_caption_batch(batch, base_url=base_url, api_key=api_key, model=model))
        except Exception as exc:  # noqa: BLE001 — one bad batch must not discard useful tool text
            # API errors can embed request context; never log image data or the exception message.
            status = getattr(exc, "status_code", None)
            status_text = f" HTTP {status}" if isinstance(status, int) else ""
            log.warning(
                "visual caption batch failed (%d image(s)): %s%s",
                len(batch),
                type(exc).__name__,
                status_text,
            )
            if status in _PERMANENT_ENDPOINT_STATUSES:
                captions.extend([None] * (len(images) - start))
                break
            captions.extend([None] * len(batch))
    return captions


def _caption_batch(
    images: list[dict[str, Any]],
    *,
    base_url: str,
    api_key: str,
    model: str,
) -> list[str]:
    """Call the shared VL client once and parse exactly one caption per image."""
    from shared.api_openai import call_openai_chat

    content: list[dict[str, Any]] = []
    for block in images:
        mime = block.get("mimeType", "image/jpeg")
        if not isinstance(mime, str) or not mime.startswith("image/"):
            mime = "image/jpeg"
        content.append(
            {
                "type": "image_url",
                "image_url": {"url": f"data:{mime};base64,{block['data']}"},
            }
        )
    content.append({"type": "text", "text": _CAPTION_PROMPT})

    response = call_openai_chat(
        base_url=base_url,
        api_key=api_key,
        model=model,
        messages=[{"role": "user", "content": content}],
        max_tokens=_CAPTION_MAX_TOKENS,
        temperature=0,
        # Never let rejection of the optional JSON hint re-enable model reasoning.
        extra_body={"enable_thinking": False},
        optional_extra_body={"response_format": {"type": "json_object"}},
    )
    parsed = _parse_captions(_response_text(response), len(images))
    if parsed is None:
        raise ValueError("caption endpoint did not return the requested captions JSON")
    return parsed


def _response_text(response: Any) -> str:
    """Extract text from the OpenAI-compatible chat response shape."""
    content = response.choices[0].message.content
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for item in content:
            value = item.get("text") if isinstance(item, dict) else getattr(item, "text", None)
            if isinstance(value, str):
                parts.append(value)
        return "".join(parts)
    return ""


def _parse_captions(raw: str, expected: int) -> list[str] | None:
    """Parse a JSON object/list, tolerating a surrounding Markdown fence or short preamble."""
    text = raw.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    candidates = [text]
    first, last = text.find("{"), text.rfind("}")
    if 0 <= first < last:
        candidates.append(text[first : last + 1])

    payload: Any = None
    for candidate in candidates:
        try:
            payload = json.loads(candidate)
            break
        except (TypeError, json.JSONDecodeError):
            continue
    if isinstance(payload, dict):
        payload = payload.get("captions")
    if not isinstance(payload, list) or len(payload) != expected:
        return None
    captions = [item.strip() for item in payload if isinstance(item, str)]
    if len(captions) != expected or any(not item for item in captions):
        return None
    return captions
